### ISSUE TITLE
Random segfault

### ISSUE THREAD

**Issue by Grsaiago** [Grsaiago/minishell#68]
![image](https://user-images.githubusercontent.com/98427284/233858539-7691f256-56a7-4e6f-827f-bd8f0de8d542.png)
Fix this.

probably the node clean on the sentence is not working properly.

**Comment by Grsaiago** [comment]
" ls | wc >oie | grep "a" " works just fine tho

**Comment by KCarriolo** [comment]
I just added a function to deal with the segfault issue.

The segfault issue is due a erroneous free on a node in the last functions of the program before it ends.
I'm having a problem with the "if" statement tho. Too tired to trying fix it by now lol

I have pushed all the progress to the branch that i just created.

**Comment by KCarriolo** [comment]
Issue fixed using another approach. 

Instead of solve the problem on the execution of the last function before program ends(ms_lstclear) a closer look was take by searching for the issue on it's very start, that is, in "ms_executor" function specifically when there isn't a valid flag in a node.

After cleaning invalid nodes for the first time, a call of the "clean_sentence_redirections" is made passing as his first parameter a "t_word **aux" node that is used to clean the invalid nodes and reatribute the head of the linked list without losing his reference and a "int flag". This parameters will make the function always clear invalid nodes and reatributes the consecutives ones to the correct head node in the list.
